export * from './footer-links';
export * from './footer-payment-data';
export * from './footer-socials-data';
export * from './contacts-links';
export * from './services.data';
export * from './slides-data';
export * from './testimonials.data';
export * from './header-links';
export * from './filters-data';