import type { Metadata } from "next";
import { Nunito, Playfair_Display } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const nunitoSans = Nunito({
   variable: "--font-nunito-sans",
   subsets: ["latin", "cyrillic"],
});

const playfair = Playfair_Display({
   variable: "--font-playfair",
   subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
   title: "Туристическое агентство",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${nunitoSans.variable} ${playfair.variable} antialiased`}
         >
            <Toaster position="top-right" />
            {children}
         </body>
      </html>
   );
}
