import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunitoSans = Nunito({
   variable: "--font-nunito-sans",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Интернет-магазин | туристическое агенство",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${nunitoSans.className} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
